[package]
name = "aws-sg-util"
version = "0.1.0"
authors = ["Jonathan Constantinides <jonleecon@gmail.com>"]

[dependencies]
clap = "2.26.2"
rusoto_core = "0.28.0"
rusoto_ec2 = "0.28.0"
error-chain = "0.11.0"
csv = "0.15.0"
trust-dns = "0.11.3"

[profile.release]
lto = true